# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-server" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "204cad8fc99b46113423562b6b6408694e7f0f06d0e726c862264f046661f8cd"
      url "https://github.com/HiveStatusDev/mcp-server/releases/download/v#{version}/mcp-server_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ae2df936ad9813371ef244d8f645808c923575287e39ab99dd3a28b750aa56b7"
      url "https://github.com/HiveStatusDev/mcp-server/releases/download/v#{version}/mcp-server_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3bc678337fd2fb41aea4afc7f20a088638656525af431c4d0532f36fbd1d74fc"
      url "https://github.com/HiveStatusDev/mcp-server/releases/download/v#{version}/mcp-server_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "333843c4d6fa8cd0a767e62bc7759e44e71d3b7394f10f352e8a47ce5501344a"
      url "https://github.com/HiveStatusDev/mcp-server/releases/download/v#{version}/mcp-server_Linux_arm64.tar.gz"
    end
  end

  name "mcp-server"
  desc "MCP-Server for HiveStatus.Cloud"
  homepage "https://github.com/HiveStatusDev/mcp-server"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-server"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hivestatus-mcp-server"]
    end
  end

  # No zap stanza required

end
