# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-server" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/HiveStatusDev/mcp-server/releases/download/v#{version}/mcp-server_Darwin_x86_64.tar.gz"
      sha256 "52f0005abdce3bce124b5db73efd592f18c36bfd04b908534a0379ac486a9de8"
    end
    on_arm do
      url "https://github.com/HiveStatusDev/mcp-server/releases/download/v#{version}/mcp-server_Darwin_arm64.tar.gz"
      sha256 "fc56b44ea6f59f98c73b75f5838b58c52b62ca41e2293a5c3e7542724270ddd2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/HiveStatusDev/mcp-server/releases/download/v#{version}/mcp-server_Linux_x86_64.tar.gz"
      sha256 "25205e1997eee9527be59af2f21f19232e7ce3e2e9632a760f8faf240cc352ad"
    end
    on_arm do
      url "https://github.com/HiveStatusDev/mcp-server/releases/download/v#{version}/mcp-server_Linux_arm64.tar.gz"
      sha256 "9a15d4883b3d5d8a140a68bb9d240896ea403275d6b6ce208fee07bc3b048a75"
    end
  end

  name "mcp-server"
  desc "MCP-Server for HiveStatus.Cloud"
  homepage "https://github.com/HiveStatusDev/mcp-server"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-server"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hivestatus-mcp-server"]
    end
  end

  # No zap stanza required

end
